[env:cardputer-adv]
platform = espressif32@6.7.0
board    = esp32-s3-devkitc-1
framework = arduino

board_build.flash_size  = 8MB
board_upload.flash_size = 8MB
board_build.partitions  = default_8MB.csv

monitor_speed = 115200
upload_speed  = 1500000

build_flags =
    -DESP32S3
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DARDUINO_USB_MODE=1
    -DCORE_DEBUG_LEVEL=3
    -O2

lib_deps =
    M5Cardputer=https://github.com/m5stack/M5Cardputer
